[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "bun run build",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh"

[staticAssets]
"dist" = "/"

[variables]
PORT = "3000"
NODE_ENV = "production"

